services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./config:/database
      - ../media:/srv
    ports:
      - 8091:80
    networks:
      - default
      - mediaservices

networks:
  default:
  mediaservices:
    external: true 