services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '${HTTP_PORT:-80}:80'
      - '${ADMIN_PORT:-9081}:81'
      - '${HTTPS_PORT:-443}:443'
    environment:
      DB_POSTGRES_HOST: "postgres"
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: "${DB_USER:-npm}"
      DB_POSTGRES_PASSWORD: "${DB_PASSWORD:-npm_password}"
      DB_POSTGRES_NAME: "${DB_NAME:-npm}"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - npm_network
      - postgresql_default

# Usaremos el contenedor PostgreSQL principal
networks:
  npm_network:
    driver: bridge
  postgresql_default:
    external: true